var searchData=
[
  ['connection_0',['Connection',['../d6/d5e/classcpp__restapi_1_1CurlBackend_1_1Connection.html#ad022f295f7ac2ea83124e6835d19bd47',1,'cpp_restapi::CurlBackend::Connection::Connection(const std::string &amp;address, const std::map&lt; std::string, std::string &gt; &amp;headerEntries)'],['../d6/d5e/classcpp__restapi_1_1CurlBackend_1_1Connection.html#aa122d5104272e78ab96656cb14389c91',1,'cpp_restapi::CurlBackend::Connection::Connection(const Connection &amp;)=delete'],['../d2/dbb/classcpp__restapi_1_1QtBackend_1_1Connection.html#a2130930b8b175fb481a4097bc7a92f25',1,'cpp_restapi::QtBackend::Connection::Connection(QNetworkAccessManager &amp;, const std::string &amp;address, const std::map&lt; std::string, std::string &gt; &amp;headerEntries)'],['../d2/dbb/classcpp__restapi_1_1QtBackend_1_1Connection.html#a2cae7b29cad0fe2d6dc9c6f22678bbb6',1,'cpp_restapi::QtBackend::Connection::Connection(const Connection &amp;)=delete'],['../d6/d5e/classcpp__restapi_1_1CurlBackend_1_1Connection.html',1,'cpp_restapi::CurlBackend::Connection'],['../d2/dbb/classcpp__restapi_1_1QtBackend_1_1Connection.html',1,'cpp_restapi::QtBackend::Connection']]],
  ['connection_5fbuilder_2ehpp_1',['connection_builder.hpp',['../d7/dd4/connection__builder_8hpp.html',1,'']]],
  ['connectionbuilder_2',['ConnectionBuilder',['../d3/dd8/classcpp__restapi_1_1GitHub_1_1ConnectionBuilder.html#a7fffe44745e2b38e13c95dc88d02c808',1,'cpp_restapi::GitHub::ConnectionBuilder::ConnectionBuilder()'],['../d3/dd8/classcpp__restapi_1_1GitHub_1_1ConnectionBuilder.html#a02daea0a18ccaf4f75042c5063c5bf84',1,'cpp_restapi::GitHub::ConnectionBuilder::ConnectionBuilder(const ConnectionBuilder &amp;)=delete'],['../d3/dd8/classcpp__restapi_1_1GitHub_1_1ConnectionBuilder.html',1,'cpp_restapi::GitHub::ConnectionBuilder']]],
  ['cpp_5frestapi_3',['cpp_restapi',['../de/db6/namespacecpp__restapi.html',1,'']]],
  ['curl_5fconnection_2ehpp_4',['curl_connection.hpp',['../de/d0e/curl__connection_8hpp.html',1,'']]],
  ['curlbackend_5',['CurlBackend',['../d2/dc6/namespacecpp__restapi_1_1CurlBackend.html',1,'cpp_restapi']]],
  ['github_6',['GitHub',['../dc/de3/namespacecpp__restapi_1_1GitHub.html',1,'cpp_restapi']]],
  ['qtbackend_7',['QtBackend',['../d1/d12/namespacecpp__restapi_1_1QtBackend.html',1,'cpp_restapi']]]
];
