name: Build-Linux-Qt6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-13, cxx: g++-13 }
          - { cc: clang-18, cxx: clang++-18 }

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false

    - uses: ./.github/actions/setup-linux
      with:
        extra-packages: qt6-base-dev

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DCppRestAPI_Tests=ON -DCppRestAPI_UseQt6=ON -DCppRestAPI_Examples=ON -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
        run-test: true
