
name: Build-Linux-Qt5

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Install system dependencies
      run: |
        sudo apt-get update &&  \
        sudo apt-get install    \
          ninja-build           \
          libgmock-dev          \
          qtbase5-dev           \
          libcurl4-openssl-dev  \
          libcpp-httplib-dev    \
          libjsoncpp-dev

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DCppRestAPI_Tests=ON -DCppRestAPI_UseQt6=OFF
        run-test: true

    - name: Build Examples
      uses: ashutoshvarma/action-cmake-build@master
      with:
        source-dir: ${{ github.workspace }}/examples
        build-dir: ${{ runner.workspace }}/build-examples
        build-type: Release
