
name: Build-Linux-Qt6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false

    - name: Install system dependencies
      run: |
        sudo apt-get update &&  \
        sudo apt-get install    \
          ninja-build           \
          libgmock-dev          \
          qt6-base-dev          \
          libcurl4-openssl-dev  \
          libcpp-httplib-dev    \
          libjsoncpp-dev        \
          valgrind

    - name: Configure (${{ matrix.compiler.cc }})
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
          -DCppRestAPI_Tests=ON \
          -DCppRestAPI_UseQt6=ON \
          -DCppRestAPI_Examples=ON

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Run tests under Valgrind (on failure)
      if: failure()
      run: valgrind --track-origins=yes --show-reachable=yes --num-callers=20 build/tests/api_tests --gtest_filter="ConnectionTest/0.*" 2>&1
