
name: Build-Linux-Qt6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false

    - name: Install system dependencies
      run: |
        sudo apt-get update &&  \
        sudo apt-get install    \
          ninja-build           \
          libgmock-dev          \
          qt6-base-dev          \
          libcurl4-openssl-dev  \
          libjsoncpp-dev

    - name: Install cpp-httplib from source
      run: |
        git clone --depth 1 https://github.com/yhirose/cpp-httplib.git /tmp/cpp-httplib
        cmake -B /tmp/cpp-httplib/build -S /tmp/cpp-httplib -DHTTPLIB_USE_ZSTD_IF_AVAILABLE=OFF
        sudo cmake --install /tmp/cpp-httplib/build

    - name: Configure (${{ matrix.compiler.cc }})
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
          -DCppRestAPI_Tests=ON \
          -DCppRestAPI_UseQt6=ON \
          -DCppRestAPI_Examples=ON

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

