name: Build-macOS-Qt6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false

    - name: Install system dependencies
      run: |
        brew install           \
          ninja                \
          googletest           \
          qt@6                 \
          curl                 \
          cpp-httplib          \
          jsoncpp

    - name: Set Qt6 prefix path
      run: echo "CMAKE_PREFIX_PATH=$(brew --prefix qt@6)" >> "$GITHUB_ENV"

    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        configure-options: -DCppRestAPI_Tests=ON -DCppRestAPI_UseQt6=ON -DCppRestAPI_Examples=ON -DCMAKE_PREFIX_PATH=${{ env.CMAKE_PREFIX_PATH }}
        run-test: true
